execution_engine: asyncio
logger:
  transports: [console]
  level: debug
  path: "logs/mcp-agent.jsonl"

mcp:
  servers:
    fetch:
      command: "uvx"
      args: ["mcp-server-fetch"]
      description: "Fetch content from URLs"    
    sqlite:
      command: "uvx"
      args: ["mcp-server-sqlite", "--db-path",  "./chinook.db"]
      description: "Query database"

bedrock:
  default_model: "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
