
[project]
name = "lesson-3"
version = "0.1.0"
description = "MCP SQL Database Example"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.10.5",
    "langchain-aws>=0.2.28",
    "langchain-mcp-adapters>=0.1.9",
    "langgraph>=0.5.3",
    "sqlite3",
]
